### ISSUE TITLE
[FEAT] message relay

### ISSUE THREAD

**Issue by rich1488** [GoByeBye/Ares#32]
relay messages from 1 server into another.

**Comment by GoByeBye** [comment]
I doubt I'll ever do this. Mostly because there are already dedicated bots for this and there's really no reason for this tbh

**Comment by rich1488** [comment]
which ones?

**Comment by GoByeBye** [comment]
A good example would be heimdall(maybe it was called hydra unsure) they had a "phone" feature where it would connect two guilds. But still, it's not something you would make in the scope of a bot

**Comment by rich1488** [comment]
heimdall just relays messages between discord and telegram.

im looking for something, that can relay messages from another discord server, from a selected channel. either all messages or just messages that have a keyword. for example;

server A, wants messages relayed from server B
selfbot sits in server B, when it detects message to relay, it sends it to a server A (real) bot
real bot relays that message in a selected channel

this is way, no one could figure out how messages are relayed cause selfbot isn't even in server A.


I have a function of this somewhat working, but the creator isnt around anymore. some relays dont work, and i need some changed and added..
