### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ehemm** [GoByeBye/Ares#33]
**Describe the bug**

**To Reproduce**
1. Run command... python selfbot.py
2. Do .... The config steps
3. ... And so on Finish N-Word loggin

**Expected behavior**
You get this
 Traceback (most recent call last):
  File "setupWizard.py", line 191, in <module>
    run_wizard()
  File "setupWizard.py", line 135, in run_wizard
    if nword.tolower is not "no" or "n":
AttributeError: 'str' object has no attribute 'tolower'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10 x64
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Additional context**

**Comment by GoByeBye** [comment]
Ah, I see. Will fix it and push ASAP. Thanks for submitting the report @Ehemm

**Comment by GoByeBye** [comment]
Fixed
